<template>
  <v-table density="compact" fixed-header striped="even">
    <thead>
      <tr>
        <th class="text-left">Date</th>
        <th class="text-left">Time</th>
        <th class="text-left">Report</th>
        <th class="text-left">Generated by</th>
        <th class="text-left">Filter Used</th>
        <th class="text-left">File</th>
        <th class="text-left">Size</th>
        <th class="text-left">Download</th>
      </tr>
    </thead>
    <tbody>
      <tr v-if="loading">
        <td colspan="7" class="text-center py-6">
          <v-progress-circular indeterminate color="primary" size="24" />
        </td>
      </tr>
      <tr v-else-if="logs.length === 0">
        <td colspan="7" class="text-center py-6 text-grey">No exports found.</td>
      </tr>
      <tr v-for="log in logs" v-else :key="log.id">
        <td class="whitespace-nowrap">{{ formatDate(log.generated_at) }}</td>
        <td class="whitespace-nowrap">{{ formatTime(log.generated_at) }}</td>
        <td>{{ log.label }}</td>
        <td>{{ log.user?.name || 'N/A' }}</td>
        <td>
          <tr><td><v-chip size="small" color="info" class="flex items-center gap-2 mb-2" v-if="log.filters?.from">From:{{ log.filters?.from || 'N/A' }}</v-chip></td></tr>
          <tr><td><v-chip size="small" color="info" class="flex items-center gap-2 mb-2" v-if="log.filters?.to">To:{{ log.filters?.to || 'N/A' }}</v-chip></td></tr>
          <tr><td><v-chip size="small" color="info" class="flex items-center gap-2 mb-2" v-if="log.filters?.cfdiOption">{{ log.filters?.cfdiOption }}</v-chip></td></tr>
          <tr><td><v-chip size="small" color="info" class="flex items-center gap-2 mb-2" v-if="log.filters?.invoice_number"># Invoice:{{ log.filters?.invoice_number }}</v-chip></td></tr>
        </td>
        <td>{{ log.file_name }}</td>
        <td class="whitespace-nowrap">{{ formatSize(log.file_size) }}</td>
        <td>
          <v-btn
            size="small"
            variant="tonal"
            color="primary"
            prepend-icon="mdi-download"
            :loading="downloadingId === log.id"
            @click="$emit('download', log)"
          >
            Download
          </v-btn>
        </td>
      </tr>
    </tbody>
  </v-table>
</template>

<script setup lang="ts">
import type { IExportLog } from '~/repository/modules/exportLogs'

defineProps<{
  logs: IExportLog[]
  loading: boolean
  downloadingId: number | null
}>()

defineEmits<{
  download: [log: IExportLog]
}>()

const formatDate = (value: string) => new Date(value).toLocaleDateString()
const formatTime = (value: string) => new Date(value).toLocaleTimeString()

const formatSize = (bytes: number) => {
  if (!bytes) return '-'
  const kb = bytes / 1024
  return kb < 1024 ? `${kb.toFixed(1)} KB` : `${(kb / 1024).toFixed(1)} MB`
}
</script>
